modLoader = "javafml"
loaderVersion = "[40,)"
license = "GNU LGPLv3"

[[mods]]
modId = "biggerstacks"
version = "${file.jarVersion}"
displayName = "Bigger Stacks"
logoFile = "BiggerStacks.png"
authors = "PORTB"
description = '''Allows increasing stack sizes past 64 up to MAXINT/2 (about 1 billion)'''

[[dependencies.biggerstacks]]
modId = "forge"
mandatory = true
versionRange = "[40.1.44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biggerstacks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"

#SC has had code changes, require a version that will work properly
[[dependencies.biggerstacks]]
modId = "sophisticatedcore"
mandatory = false
versionRange = "[1.18.2-0.5.48-alpha,)"
ordering = "NONE"
side = "BOTH"
