modLoader = "javafml"
loaderVersion = "[39,)"
license = "GNU LGPLv3"

[[mods]]
modId = "biggerstacks"
version = "${file.jarVersion}"
displayName = "Bigger Stacks"
logoFile="BiggerStacks.png"
authors="PORTB"
description = '''
Allows increasing stack sizes past 64 up to MAXINT (about 2 billion)
'''

[[dependencies.biggerstacks]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biggerstacks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1]"
ordering = "NONE"
side = "BOTH"
